### ISSUE TITLE
Error: [$injector:modulerr] Failed to instantiate module

### ISSUE THREAD

**Issue by devonCream** [EE/karma-ng-json2js-preprocessor#9] opened 2015-01-16 08:27 UTC
Following the instruction I have used this plug in to load a json file into my angular karma unit tests.
With Firefox this works fine, I can get access to the data file and test with it, but with IE9 the same unit tests fail with:

	Error: [$injector:modulerr] Failed to instantiate module testFile.json due to:
	[$injector:nomod] Module 'testFile.json' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
	http://errors.angularjs.org/1.2.16/$injector/nomod?p0=testFile.json
	http://errors.angularjs.org/1.2.16/$injector/modulerr?p0=testFile.json&p1=%5B%24injector%3Anomod%5D%20Module%20'testFile.json'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.2.16%2F%24injector%2Fnomod%3Fp0%3DtestFile.json
	Expected undefined to be defined.

**Comment by wedgybo** [comment] 2015-01-16 15:34
I'm having the same issue. The problem appears to be that the generated script is not being dynamically added into the page in the dynamic scripts section of injected by karma. Even though __karma__.files has the file listed. Will keep digging

**Comment by mzgol** [comment] 2015-01-20 22:21
@devonCream Angular 1.2.16 is very old, can you try with 1.2.28? Does the problem appear on Angular 1.3.10 as well? Also, please post your package.json so that I can see what versions of packages you use. Do you use [karma-ie-launcher](https://github.com/karma-runner/karma-ie-launcher)?

@wedgybo could you answer the same questions?

The file generates a plain Angular module, I'm surprised anything there can be browser-specific...

**Comment by mzgol** [comment] 2015-01-20 22:22
If anyone is able to point me to a public repository where it fails so that I could try it myself, that'd be great!

**Comment by wedgybo** [comment] 2015-01-20 22:26
I'm using ionicframework so it's on 1.3.5 at the moment. I'm afraid the repository isn't public. I tried debugging but ran out of time on it. I got as far as working out that karma appears to know about the files in the mappings array, but not in the files.include so the script tag for it isn't never injected.

```json
{
  "name": "runway",
  "version": "2.1.0",
  "private": true,
  "dependencies": {
    "bower": "^1.3.12"
  },
  "devDependencies": {
    "grunt": "~0.4.1",
    "grunt-bump": "0.0.16",
    "grunt-contrib-clean": "~0.4.0",
    "grunt-contrib-compress": "^0.5.3",
    "grunt-contrib-concat": "^0.1.3",
    "grunt-contrib-connect": "^0.8.0",
    "grunt-contrib-copy": "^0.4.1",
    "grunt-contrib-cssmin": "^0.5.0",
    "grunt-contrib-htmlmin": "^0.1.3",
    "grunt-contrib-imagemin": "^0.1.4",
    "grunt-contrib-jshint": "~0.10.0",
    "grunt-contrib-livereload": "~0.1.2",
    "grunt-contrib-sass": "^0.7.4",
    "grunt-contrib-uglify": "^0.2.7",
    "grunt-html": "^1.4.0",
    "grunt-html2js": "~0.2.3",
    "grunt-karma": "^0.8.3",
    "grunt-newer": "^0.7.0",
    "grunt-ng-annotate": "^0.4.0",
    "grunt-ng-constant": "^0.5.0",
    "grunt-open": "~0.2.0",
    "grunt-phonegap-build": "~0.0.6",
    "grunt-protractor-runner": "^1.0.0",
    "grunt-regarde": "~0.1.1",
    "grunt-release": "^0.7.0",
    "grunt-rev": "~0.1.0",
    "grunt-s3": "~0.2.0-alpha.3",
    "grunt-usemin": "^0.1.13",
    "karma": "^0.12.31",
    "karma-chai": "^0.1.0",
    "karma-chrome-launcher": "^0.1.7",
    "karma-fixture": "^0.2.1-1",
    "karma-html2js-preprocessor": "^0.1.0",
    "karma-mocha": "^0.1.10",
    "karma-ng-json2js-preprocessor": "^1.0.0",
    "karma-osx-reporter": "^0.1.0",
    "karma-phantomjs-launcher": "^0.1.4",
    "karma-sinon": "^1.0.4",
    "karma-sinon-chai": "^0.2.0",
    "karma-story-reporter": "^0.2.2",
    "load-grunt-config": "^0.13.2",
    "load-grunt-tasks": "^0.6.0",
    "matchdep": "^0.1.2",
    "mocha": "^2.1.0",
    "pivotal-deliver": "^0.1.0",
    "sinon": "^1.12.2",
    "time-grunt": "^1.0.0"
  },
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "postinstall": "./tasks/postinstall.sh"
  }
}
```

**Comment by mzgol** [comment] 2015-01-20 23:49
@wedgybo I don't see `karma-ie-launcher` in your config; on what browser exactly do you experience problems?

**Comment by wedgybo** [comment] 2015-01-21 00:11
I was seeing it in chrome

**Comment by mzgol** [comment] 2015-01-21 01:10
If Karma is not finding the file even though the pre-processor did generate it then I'm not sure what else I can do here. It seems to be a Karma bug.

BTW, I've just landed a [commit](https://github.com/EE/karma-ng-json2js-preprocessor/commit/a4fd32cf247d2fc82d431e73696e3bb42d21cc4e) testing on Travis on [real browsers, including IE9](https://travis-ci.org/EE/karma-ng-json2js-preprocessor/builds/47727638).

**Comment by devonCream** [comment] 2015-01-21 19:03
Hi, Indeed 1.2.16 is old, but we had to support IE8 at the time, we have now dropped this and are in the process of updating to 1.3.
Yes I am using Karma Ie launcher
Our repo is internal as its a commercial product so I can't give you access to this.
I'm at home at the moment, so can't get the package info, will try to get tomorrow.

**Comment by mzgol** [comment] 2015-01-24 18:14
> Indeed 1.2.16 is old, but we had to support IE8 at the time

I meant that it's an old 1.2.* release. You should update to 1.2.28 and check if the problem still exist.

**Comment by mzgol** [comment] 2015-01-24 18:16
OK folks, I started testing on real browsers and the test pass. Without an example (preferrably minimal) on which I could reproduce the failure I don't know how to find the issue.

**Comment by mzgol** [comment] 2015-02-19 14:15
Due to lacking information I'm closing this issue. If anyone has a test case I could look at, comment here and I'll reopen.

**Closed by mzgol** 2015-02-19 14:15 UTC
